# configs/default_config.yaml
detection:
  confidence_threshold: 0.5
  model_path: 'models/yolov8n.pt'
  available_models:
    - 'yolov8n.pt'
    - 'yolov8s.pt'
    - 'yolov8m.pt'

tracking:
  enabled: false
  history_length: 50

output:
  output_dir: 'detection_output'
  save_detections: true
  save_video: false

ui:
  show_fps: true
  show_confidence: true
  show_labels: true
  show_boxes: true

zones:
  enabled: false
  max_zones: 5